/** Every official upload, shown 1:1 in the Codex and as battle/status art. */

export interface ArtPage {
  key: string;
  title: string;
  url: string;
}

export const ART: ArtPage[] = [
  { key: "art-opening", title: "OPENING SCENE", url: "/game/art/opening.jpg" },
  { key: "art-baki-head", title: "BAKI HEAD SHOT", url: "/game/art/baki-head.jpg" },
  { key: "art-baki-overworld", title: "BAKI MAIN CHARACTER", url: "/game/art/baki-overworld.jpg" },
  { key: "art-baki-battle", title: "BAKI IN BATTLE", url: "/game/art/baki-battle.jpg" },
  { key: "art-baki-attack", title: "BAKI MOVING AND ATTACKING", url: "/game/art/baki-attack.jpg" },
  { key: "art-menu", title: "MENU", url: "/game/art/menu.jpg" },
  { key: "art-map", title: "MAP AND LOCATIONS", url: "/game/art/map.jpg" },
  { key: "art-chibi", title: "BACKGROUNDS · CHARACTERS · ENEMIES", url: "/game/art/chibi.jpg" },
  { key: "art-illuminati", title: "ILLUMINATI", url: "/game/art/illuminati.jpg" },
  { key: "art-innkeeper", title: "SHOP OWNER", url: "/game/art/innkeeper.jpg" },
  { key: "art-crusader", title: "CHRISTIAN ZIONIST", url: "/game/art/crusader.jpg" },
  { key: "art-propagandist", title: "PROPAGANDIST", url: "/game/art/propagandist.jpg" },
  { key: "art-knight", title: "MAGA KNIGHT", url: "/game/art/knight.jpg" },
  { key: "art-sheep", title: "INTERNET SHEEP", url: "/game/art/sheep.jpg" },
  { key: "art-corporate", title: "CORPORATE SLAVE", url: "/game/art/corporate.jpg" },
  { key: "art-mage", title: "WIZARD", url: "/game/art/mage.jpg" },
  { key: "art-activist", title: "ACTIVIST", url: "/game/art/activist.jpg" },
  { key: "art-berserker", title: "SJW", url: "/game/art/berserker.jpg" },
  { key: "art-sheeple", title: "SHEEPLE HOMELESS", url: "/game/art/sheeple.jpg" },
  { key: "art-captain", title: "R&D / CULTURE WAR", url: "/game/art/captain.jpg" },
  { key: "art-puppet", title: "CABLE NEWS", url: "/game/art/puppet.jpg" },
  { key: "art-slime", title: "SOCIAL MEDIA ECHO CHAMBER", url: "/game/art/slime.jpg" },
  { key: "art-instructor", title: "RE-EDUCATION INSTRUCTOR", url: "/game/art/instructor.jpg" },
  { key: "art-rothschild", title: "LORD ROTHSCHILD", url: "/game/art/rothschild.jpg" },
  { key: "art-rockefeller", title: "ROCKEFELLER", url: "/game/art/rockefeller.jpg" },
  { key: "art-astor", title: "ASTOR", url: "/game/art/astor.jpg" },
  { key: "art-bundy", title: "BUNDY RANCH WARLORD", url: "/game/art/bundy.jpg" },
  { key: "art-collins", title: "COLLINS", url: "/game/art/collins.jpg" },
  { key: "art-dupont", title: "DUPONT CHEMICAL ALCHEMIST", url: "/game/art/dupont.jpg" },
  { key: "art-freeman", title: "RADIO PROPAGANDIST", url: "/game/art/freeman.jpg" },
  { key: "art-kennedy", title: "KENNEDY DYNASTY PALADIN", url: "/game/art/kennedy.jpg" },
  { key: "art-li", title: "LI DRAGON FINANCE EMPEROR", url: "/game/art/li.jpg" },
  { key: "art-onassis", title: "ONASSIS SHIPPING", url: "/game/art/onassis.jpg" },
  { key: "art-lobbyist", title: "LOBBYIST", url: "/game/art/lobbyist.jpg" },
  { key: "art-russell", title: "RUSSELL WATCHTOWER SENTINEL", url: "/game/art/russell.jpg" },
  { key: "art-vanduyn", title: "VAN DUYN SERPENT DIPLOMAT", url: "/game/art/vanduyn.jpg" },
  { key: "art-merovingian", title: "WARLOCK / MEROVINGIAN", url: "/game/art/merovingian.jpg" },
];

export const ENEMY_PORTRAIT: Record<string, string> = {
  faith_first_crusader: "art-crusader",
  no_apologies_brawler: "art-propagandist",
  pragmatic_polite: "art-knight",
  unconventional_rogue: "art-sheep",
  loyal_liberal_mage: "art-mage",
  leftward_progressive: "art-activist",
  order_opportunity: "art-corporate",
  left_out_berserker: "art-berserker",
  tuned_out_middle: "art-sheeple",
  culture_war_captain: "art-captain",
  cable_news_puppet: "art-puppet",
  echo_chamber_slime: "art-slime",
  reeducation_instructor: "art-instructor",
  rothschild_archon: "art-rothschild",
  rockefeller_titan: "art-rockefeller",
  astor_phantom: "art-astor",
  bundy_warlock: "art-bundy",
  collins_necromancer: "art-collins",
  dupont_alchemist: "art-dupont",
  freeman_hypnotist: "art-freeman",
  kennedy_paladin: "art-kennedy",
  li_emperor: "art-li",
  onassis_hydra: "art-onassis",
  reynolds_demon: "art-lobbyist",
  russell_sentinel: "art-russell",
  vanduyn_diplomat: "art-vanduyn",
  merovingian_king: "art-merovingian",
};
